import { NextRequest, NextResponse } from "next/server";
import { requireApiAuth } from "@/lib/api-guard";

export interface CatalogueEntry {
  provider: string;
  category: string;
  name: string;
  description: string;
  authType: "OAUTH2" | "API_KEY" | "SAML" | "WEBHOOK" | "MQTT" | "CUSTOM";
  syncDirection: "INBOUND" | "OUTBOUND" | "BIDIRECTIONAL";
  webhookSupport: boolean;
  docsUrl: string;
  logoEmoji: string;
  popularity: "HIGH" | "MEDIUM" | "LOW";
  setupComplexity: "LOW" | "MEDIUM" | "HIGH" | "ENTERPRISE";
  connectorRoute?: string;
}

const CATALOGUE: CatalogueEntry[] = [
  // ── ACCOUNTING ────────────────────────────────────────────────────────────
  {
    provider: "QUICKBOOKS",
    category: "ACCOUNTING",
    name: "QuickBooks Online",
    description: "Sync invoices, bills, and P&L with QuickBooks Online.",
    authType: "OAUTH2",
    syncDirection: "BIDIRECTIONAL",
    webhookSupport: true,
    docsUrl: "https://developer.intuit.com",
    logoEmoji: "🟢",
    popularity: "HIGH",
    setupComplexity: "LOW",
  },
  {
    provider: "XERO",
    category: "ACCOUNTING",
    name: "Xero",
    description:
      "Cloud accounting — sync purchases, supplier invoices and COGS.",
    authType: "OAUTH2",
    syncDirection: "BIDIRECTIONAL",
    webhookSupport: true,
    docsUrl: "https://developer.xero.com",
    logoEmoji: "🔵",
    popularity: "HIGH",
    setupComplexity: "LOW",
  },
  {
    provider: "SAGE",
    category: "ACCOUNTING",
    name: "Sage Business Cloud",
    description: "Sync stock valuation and financial journals with Sage.",
    authType: "OAUTH2",
    syncDirection: "BIDIRECTIONAL",
    webhookSupport: false,
    docsUrl: "https://developer.sage.com",
    logoEmoji: "🟩",
    popularity: "MEDIUM",
    setupComplexity: "MEDIUM",
  },
  {
    provider: "NETSUITE",
    category: "ACCOUNTING",
    name: "Oracle NetSuite",
    description: "Real-time inventory and financial sync with NetSuite ERP.",
    authType: "OAUTH2",
    syncDirection: "BIDIRECTIONAL",
    webhookSupport: true,
    docsUrl: "https://docs.oracle.com/en/cloud/saas/netsuite/",
    logoEmoji: "🔷",
    popularity: "HIGH",
    setupComplexity: "HIGH",
    connectorRoute: "/api/integrations/erp",
  },
  {
    provider: "FRESHBOOKS",
    category: "ACCOUNTING",
    name: "FreshBooks",
    description: "Invoice and expense sync for SMB accounting.",
    authType: "OAUTH2",
    syncDirection: "OUTBOUND",
    webhookSupport: false,
    docsUrl: "https://www.freshbooks.com/api",
    logoEmoji: "🌿",
    popularity: "LOW",
    setupComplexity: "LOW",
  },

  // ── ERP ───────────────────────────────────────────────────────────────────
  {
    provider: "SAP_S4HANA",
    category: "ERP",
    name: "SAP S/4HANA",
    description:
      "Enterprise-grade ERP — sync materials, purchase orders, GR/GI, and stock transport orders.",
    authType: "OAUTH2",
    syncDirection: "BIDIRECTIONAL",
    webhookSupport: true,
    docsUrl: "https://api.sap.com",
    logoEmoji: "🔵",
    popularity: "HIGH",
    setupComplexity: "ENTERPRISE",
    connectorRoute: "/api/integrations/erp",
  },
  {
    provider: "SAP",
    category: "ERP",
    name: "SAP ECC",
    description:
      "Legacy SAP ECC integration via RFC/IDoc for materials and inventory.",
    authType: "CUSTOM",
    syncDirection: "BIDIRECTIONAL",
    webhookSupport: false,
    docsUrl: "https://api.sap.com",
    logoEmoji: "🔵",
    popularity: "HIGH",
    setupComplexity: "ENTERPRISE",
    connectorRoute: "/api/integrations/erp",
  },
  {
    provider: "ORACLE_ERP",
    category: "ERP",
    name: "Oracle ERP Cloud",
    description:
      "Oracle Fusion Cloud ERP — inventory, procurement, and financials sync.",
    authType: "OAUTH2",
    syncDirection: "BIDIRECTIONAL",
    webhookSupport: true,
    docsUrl: "https://docs.oracle.com/en/cloud/saas/erp/",
    logoEmoji: "🔴",
    popularity: "HIGH",
    setupComplexity: "ENTERPRISE",
    connectorRoute: "/api/integrations/erp",
  },
  {
    provider: "MICROSOFT_DYNAMICS_365",
    category: "ERP",
    name: "Microsoft Dynamics 365",
    description:
      "D365 Finance & Supply Chain — items, purchase orders, warehouse transfers.",
    authType: "OAUTH2",
    syncDirection: "BIDIRECTIONAL",
    webhookSupport: true,
    docsUrl: "https://learn.microsoft.com/en-us/dynamics365/",
    logoEmoji: "🟦",
    popularity: "HIGH",
    setupComplexity: "ENTERPRISE",
    connectorRoute: "/api/integrations/erp",
  },
  {
    provider: "DYNAMICS",
    category: "ERP",
    name: "Microsoft Dynamics 365 BC",
    description:
      "Dynamics 365 Business Central for mid-market ERP integration.",
    authType: "OAUTH2",
    syncDirection: "BIDIRECTIONAL",
    webhookSupport: true,
    docsUrl: "https://docs.microsoft.com/en-us/dynamics365/business-central/",
    logoEmoji: "🟦",
    popularity: "MEDIUM",
    setupComplexity: "HIGH",
    connectorRoute: "/api/integrations/erp",
  },
  {
    provider: "ODOO",
    category: "ERP",
    name: "Odoo",
    description:
      "Open-source ERP — sync inventory, manufacturing orders, and BOM.",
    authType: "API_KEY",
    syncDirection: "BIDIRECTIONAL",
    webhookSupport: true,
    docsUrl: "https://www.odoo.com/documentation/17.0/developer/api/",
    logoEmoji: "🟣",
    popularity: "MEDIUM",
    setupComplexity: "MEDIUM",
    connectorRoute: "/api/integrations/erp",
  },

  // ── E-COMMERCE ────────────────────────────────────────────────────────────
  {
    provider: "SHOPIFY",
    category: "ECOMMERCE",
    name: "Shopify",
    description:
      "Real-time inventory sync and order fulfilment with Shopify stores.",
    authType: "OAUTH2",
    syncDirection: "BIDIRECTIONAL",
    webhookSupport: true,
    docsUrl: "https://shopify.dev",
    logoEmoji: "🛍️",
    popularity: "HIGH",
    setupComplexity: "LOW",
  },
  {
    provider: "WOOCOMMERCE",
    category: "ECOMMERCE",
    name: "WooCommerce",
    description: "Inventory and order sync with WordPress WooCommerce stores.",
    authType: "API_KEY",
    syncDirection: "BIDIRECTIONAL",
    webhookSupport: true,
    docsUrl: "https://woocommerce.github.io/woocommerce-rest-api-docs/",
    logoEmoji: "🟣",
    popularity: "HIGH",
    setupComplexity: "LOW",
  },
  {
    provider: "AMAZON",
    category: "ECOMMERCE",
    name: "Amazon Seller Central",
    description: "FBA/FBM inventory sync and order management via SP-API.",
    authType: "OAUTH2",
    syncDirection: "BIDIRECTIONAL",
    webhookSupport: false,
    docsUrl: "https://developer-docs.amazon.com/sp-api/",
    logoEmoji: "🟠",
    popularity: "HIGH",
    setupComplexity: "HIGH",
  },
  {
    provider: "EBAY",
    category: "ECOMMERCE",
    name: "eBay",
    description: "Listing and order sync with eBay marketplace.",
    authType: "OAUTH2",
    syncDirection: "BIDIRECTIONAL",
    webhookSupport: true,
    docsUrl: "https://developer.ebay.com",
    logoEmoji: "🔴",
    popularity: "MEDIUM",
    setupComplexity: "MEDIUM",
  },
  {
    provider: "ETSY",
    category: "ECOMMERCE",
    name: "Etsy",
    description: "Inventory and order management for Etsy sellers.",
    authType: "OAUTH2",
    syncDirection: "BIDIRECTIONAL",
    webhookSupport: false,
    docsUrl: "https://developers.etsy.com",
    logoEmoji: "🟠",
    popularity: "LOW",
    setupComplexity: "LOW",
  },
  {
    provider: "BIGCOMMERCE",
    category: "ECOMMERCE",
    name: "BigCommerce",
    description: "Inventory and fulfilment sync for BigCommerce stores.",
    authType: "API_KEY",
    syncDirection: "BIDIRECTIONAL",
    webhookSupport: true,
    docsUrl: "https://developer.bigcommerce.com",
    logoEmoji: "🔵",
    popularity: "MEDIUM",
    setupComplexity: "LOW",
  },
  {
    provider: "MAGENTO",
    category: "ECOMMERCE",
    name: "Adobe Commerce (Magento)",
    description:
      "Product catalogue and order sync with Magento/Adobe Commerce.",
    authType: "OAUTH2",
    syncDirection: "BIDIRECTIONAL",
    webhookSupport: true,
    docsUrl: "https://developer.adobe.com/commerce/",
    logoEmoji: "🔴",
    popularity: "MEDIUM",
    setupComplexity: "HIGH",
  },
  {
    provider: "SQUARESPACE",
    category: "ECOMMERCE",
    name: "Squarespace",
    description: "Sync inventory and orders from Squarespace stores.",
    authType: "OAUTH2",
    syncDirection: "BIDIRECTIONAL",
    webhookSupport: false,
    docsUrl: "https://developers.squarespace.com",
    logoEmoji: "⬛",
    popularity: "LOW",
    setupComplexity: "LOW",
  },

  // ── SHIPPING / CARRIERS ───────────────────────────────────────────────────
  {
    provider: "FEDEX",
    category: "SHIPPING",
    name: "FedEx",
    description:
      "Rate shopping, label generation, and shipment tracking with FedEx.",
    authType: "OAUTH2",
    syncDirection: "OUTBOUND",
    webhookSupport: true,
    docsUrl: "https://developer.fedex.com",
    logoEmoji: "🟣",
    popularity: "HIGH",
    setupComplexity: "MEDIUM",
  },
  {
    provider: "UPS",
    category: "SHIPPING",
    name: "UPS",
    description: "Label generation, rate estimates, and tracking with UPS.",
    authType: "OAUTH2",
    syncDirection: "OUTBOUND",
    webhookSupport: true,
    docsUrl: "https://developer.ups.com",
    logoEmoji: "🟤",
    popularity: "HIGH",
    setupComplexity: "MEDIUM",
  },
  {
    provider: "DHL",
    category: "SHIPPING",
    name: "DHL Express",
    description:
      "International shipping labels and real-time tracking with DHL.",
    authType: "API_KEY",
    syncDirection: "OUTBOUND",
    webhookSupport: true,
    docsUrl: "https://developer.dhl.com",
    logoEmoji: "🟡",
    popularity: "HIGH",
    setupComplexity: "MEDIUM",
  },
  {
    provider: "USPS",
    category: "SHIPPING",
    name: "USPS",
    description:
      "USPS label generation and tracking for domestic US shipments.",
    authType: "API_KEY",
    syncDirection: "OUTBOUND",
    webhookSupport: false,
    docsUrl: "https://www.usps.com/business/web-tools-apis/",
    logoEmoji: "🦅",
    popularity: "HIGH",
    setupComplexity: "LOW",
  },
  {
    provider: "ROYAL_MAIL",
    category: "SHIPPING",
    name: "Royal Mail",
    description:
      "UK carrier — Click & Drop API for label generation and tracking.",
    authType: "OAUTH2",
    syncDirection: "OUTBOUND",
    webhookSupport: false,
    docsUrl: "https://developer.royalmail.net",
    logoEmoji: "🇬🇧",
    popularity: "HIGH",
    setupComplexity: "MEDIUM",
  },
  {
    provider: "DPD",
    category: "SHIPPING",
    name: "DPD",
    description:
      "European parcel carrier — shipping labels, tracking, and predict notifications.",
    authType: "API_KEY",
    syncDirection: "OUTBOUND",
    webhookSupport: true,
    docsUrl: "https://www.dpd.com/gb/en/support/developer/",
    logoEmoji: "🔴",
    popularity: "HIGH",
    setupComplexity: "MEDIUM",
  },
  {
    provider: "SHIPSTATION",
    category: "SHIPPING",
    name: "ShipStation",
    description:
      "Multi-carrier shipping platform — orders, labels, tracking aggregated.",
    authType: "API_KEY",
    syncDirection: "BIDIRECTIONAL",
    webhookSupport: true,
    docsUrl: "https://www.shipstation.com/docs/api/",
    logoEmoji: "⚓",
    popularity: "MEDIUM",
    setupComplexity: "LOW",
  },

  // ── PAYMENT ───────────────────────────────────────────────────────────────
  {
    provider: "STRIPE",
    category: "PAYMENT",
    name: "Stripe",
    description: "Payment collection, invoicing, and billing automation.",
    authType: "API_KEY",
    syncDirection: "INBOUND",
    webhookSupport: true,
    docsUrl: "https://stripe.com/docs/api",
    logoEmoji: "💳",
    popularity: "HIGH",
    setupComplexity: "LOW",
  },
  {
    provider: "PAYPAL",
    category: "PAYMENT",
    name: "PayPal",
    description: "Accept PayPal payments and sync transaction records.",
    authType: "OAUTH2",
    syncDirection: "INBOUND",
    webhookSupport: true,
    docsUrl: "https://developer.paypal.com",
    logoEmoji: "🔵",
    popularity: "HIGH",
    setupComplexity: "LOW",
  },
  {
    provider: "SQUARE",
    category: "PAYMENT",
    name: "Square",
    description: "POS and online payment processing with Square.",
    authType: "OAUTH2",
    syncDirection: "BIDIRECTIONAL",
    webhookSupport: true,
    docsUrl: "https://developer.squareup.com",
    logoEmoji: "⬛",
    popularity: "MEDIUM",
    setupComplexity: "LOW",
  },

  // ── CRM ───────────────────────────────────────────────────────────────────
  {
    provider: "SALESFORCE",
    category: "CRM",
    name: "Salesforce",
    description:
      "Sync customers, contacts, and orders between WMS and Salesforce CRM.",
    authType: "OAUTH2",
    syncDirection: "BIDIRECTIONAL",
    webhookSupport: true,
    docsUrl: "https://developer.salesforce.com",
    logoEmoji: "☁️",
    popularity: "HIGH",
    setupComplexity: "HIGH",
  },
  {
    provider: "HUBSPOT",
    category: "CRM",
    name: "HubSpot",
    description:
      "Sync deals, contacts, and fulfilment events with HubSpot CRM.",
    authType: "OAUTH2",
    syncDirection: "BIDIRECTIONAL",
    webhookSupport: true,
    docsUrl: "https://developers.hubspot.com",
    logoEmoji: "🟠",
    popularity: "HIGH",
    setupComplexity: "MEDIUM",
  },
  {
    provider: "ZOHO",
    category: "CRM",
    name: "Zoho CRM",
    description: "Customer and order sync between WMS and Zoho CRM.",
    authType: "OAUTH2",
    syncDirection: "BIDIRECTIONAL",
    webhookSupport: true,
    docsUrl: "https://www.zoho.com/crm/developer/",
    logoEmoji: "🟢",
    popularity: "MEDIUM",
    setupComplexity: "MEDIUM",
  },
  {
    provider: "PIPEDRIVE",
    category: "CRM",
    name: "Pipedrive",
    description:
      "Sales pipeline events and deal stages synced with warehouse dispatch.",
    authType: "OAUTH2",
    syncDirection: "OUTBOUND",
    webhookSupport: true,
    docsUrl: "https://developers.pipedrive.com",
    logoEmoji: "🟢",
    popularity: "MEDIUM",
    setupComplexity: "LOW",
  },

  // ── MARKETING ─────────────────────────────────────────────────────────────
  {
    provider: "MAILCHIMP",
    category: "MARKETING",
    name: "Mailchimp",
    description:
      "Trigger dispatch confirmation emails and restock notifications.",
    authType: "OAUTH2",
    syncDirection: "OUTBOUND",
    webhookSupport: true,
    docsUrl: "https://mailchimp.com/developer/",
    logoEmoji: "🐒",
    popularity: "MEDIUM",
    setupComplexity: "LOW",
  },
  {
    provider: "KLAVIYO",
    category: "MARKETING",
    name: "Klaviyo",
    description:
      "E-commerce lifecycle emails driven by stock and order events.",
    authType: "API_KEY",
    syncDirection: "OUTBOUND",
    webhookSupport: true,
    docsUrl: "https://developers.klaviyo.com",
    logoEmoji: "🟢",
    popularity: "MEDIUM",
    setupComplexity: "LOW",
  },

  // ── COMMUNICATION ─────────────────────────────────────────────────────────
  {
    provider: "TWILIO",
    category: "COMMUNICATION",
    name: "Twilio",
    description:
      "SMS and WhatsApp alerts for order status and inventory alerts.",
    authType: "API_KEY",
    syncDirection: "OUTBOUND",
    webhookSupport: true,
    docsUrl: "https://www.twilio.com/docs",
    logoEmoji: "📱",
    popularity: "HIGH",
    setupComplexity: "LOW",
  },
  {
    provider: "SLACK",
    category: "COMMUNICATION",
    name: "Slack",
    description:
      "Push warehouse alerts and approval requests to Slack channels.",
    authType: "OAUTH2",
    syncDirection: "OUTBOUND",
    webhookSupport: true,
    docsUrl: "https://api.slack.com",
    logoEmoji: "💬",
    popularity: "HIGH",
    setupComplexity: "LOW",
  },
  {
    provider: "TEAMS",
    category: "COMMUNICATION",
    name: "Microsoft Teams",
    description:
      "Post adaptive cards for approvals and alerts into Teams channels.",
    authType: "OAUTH2",
    syncDirection: "OUTBOUND",
    webhookSupport: true,
    docsUrl: "https://docs.microsoft.com/en-us/microsoftteams/platform/",
    logoEmoji: "🟦",
    popularity: "HIGH",
    setupComplexity: "LOW",
  },
  {
    provider: "SENDGRID",
    category: "COMMUNICATION",
    name: "SendGrid",
    description:
      "Transactional email delivery for order and dispatch notifications.",
    authType: "API_KEY",
    syncDirection: "OUTBOUND",
    webhookSupport: true,
    docsUrl: "https://docs.sendgrid.com",
    logoEmoji: "🔵",
    popularity: "HIGH",
    setupComplexity: "LOW",
  },

  // ── ANALYTICS / BI ────────────────────────────────────────────────────────
  {
    provider: "POWER_BI",
    category: "BI",
    name: "Microsoft Power BI",
    description:
      "Export KPI datasets and warehouse metrics to Power BI dashboards.",
    authType: "OAUTH2",
    syncDirection: "OUTBOUND",
    webhookSupport: false,
    docsUrl: "https://docs.microsoft.com/en-us/power-bi/developer/",
    logoEmoji: "📊",
    popularity: "HIGH",
    setupComplexity: "MEDIUM",
    connectorRoute: "/api/integrations/bi",
  },
  {
    provider: "TABLEAU",
    category: "BI",
    name: "Tableau",
    description: "Push inventory and order analytics to Tableau workbooks.",
    authType: "API_KEY",
    syncDirection: "OUTBOUND",
    webhookSupport: false,
    docsUrl:
      "https://help.tableau.com/current/api/rest_api/en-us/REST/rest_api.htm",
    logoEmoji: "📈",
    popularity: "HIGH",
    setupComplexity: "MEDIUM",
    connectorRoute: "/api/integrations/bi",
  },
  {
    provider: "LOOKER",
    category: "BI",
    name: "Looker / Google Looker Studio",
    description:
      "Publish WMS metrics to Looker explore models for ad-hoc analysis.",
    authType: "API_KEY",
    syncDirection: "OUTBOUND",
    webhookSupport: false,
    docsUrl: "https://developers.looker.com",
    logoEmoji: "🔍",
    popularity: "MEDIUM",
    setupComplexity: "HIGH",
    connectorRoute: "/api/integrations/bi",
  },
  {
    provider: "QLIK",
    category: "BI",
    name: "Qlik",
    description:
      "Stream warehouse event data to Qlik Sense for associative analytics.",
    authType: "API_KEY",
    syncDirection: "OUTBOUND",
    webhookSupport: false,
    docsUrl: "https://qlik.dev",
    logoEmoji: "🟢",
    popularity: "MEDIUM",
    setupComplexity: "HIGH",
    connectorRoute: "/api/integrations/bi",
  },
  {
    provider: "DOMO",
    category: "BI",
    name: "Domo",
    description:
      "Push real-time KPIs to Domo DataSets for executive dashboards.",
    authType: "API_KEY",
    syncDirection: "OUTBOUND",
    webhookSupport: false,
    docsUrl: "https://developer.domo.com",
    logoEmoji: "🔴",
    popularity: "LOW",
    setupComplexity: "MEDIUM",
    connectorRoute: "/api/integrations/bi",
  },
  {
    provider: "GOOGLE_ANALYTICS",
    category: "ANALYTICS",
    name: "Google Analytics 4",
    description: "Track portal usage and user behaviour with GA4 events.",
    authType: "API_KEY",
    syncDirection: "OUTBOUND",
    webhookSupport: false,
    docsUrl: "https://developers.google.com/analytics",
    logoEmoji: "📉",
    popularity: "HIGH",
    setupComplexity: "LOW",
  },

  // ── HR & WORKFORCE ────────────────────────────────────────────────────────
  {
    provider: "WORKDAY",
    category: "HR",
    name: "Workday HCM",
    description:
      "Sync workers, skills, contracts, and shift assignments from Workday.",
    authType: "OAUTH2",
    syncDirection: "INBOUND",
    webhookSupport: false,
    docsUrl:
      "https://community.workday.com/sites/default/files/file-hosting/restapi/",
    logoEmoji: "🏢",
    popularity: "HIGH",
    setupComplexity: "ENTERPRISE",
    connectorRoute: "/api/integrations/hr",
  },
  {
    provider: "SAP_SUCCESSFACTORS",
    category: "HR",
    name: "SAP SuccessFactors",
    description:
      "Employee data, org structure, and time & attendance from SuccessFactors.",
    authType: "OAUTH2",
    syncDirection: "INBOUND",
    webhookSupport: false,
    docsUrl: "https://api.sap.com/package/SFSF/rest",
    logoEmoji: "🔵",
    popularity: "HIGH",
    setupComplexity: "ENTERPRISE",
    connectorRoute: "/api/integrations/hr",
  },
  {
    provider: "UKG",
    category: "HR",
    name: "UKG (Kronos)",
    description:
      "Shift schedules and time-and-attendance sync from UKG Pro / Dimensions.",
    authType: "OAUTH2",
    syncDirection: "INBOUND",
    webhookSupport: true,
    docsUrl: "https://developer.ukg.com",
    logoEmoji: "⏱️",
    popularity: "HIGH",
    setupComplexity: "HIGH",
    connectorRoute: "/api/integrations/hr",
  },
  {
    provider: "BAMBOOHR",
    category: "HR",
    name: "BambooHR",
    description: "Employee profiles and org chart sync from BambooHR.",
    authType: "API_KEY",
    syncDirection: "INBOUND",
    webhookSupport: true,
    docsUrl: "https://documentation.bamboohr.com/reference",
    logoEmoji: "🎋",
    popularity: "MEDIUM",
    setupComplexity: "LOW",
    connectorRoute: "/api/integrations/hr",
  },
  {
    provider: "HIBOB",
    category: "HR",
    name: "HiBob",
    description:
      "People data, attendance, and lifecycle events from HiBob HRIS.",
    authType: "API_KEY",
    syncDirection: "INBOUND",
    webhookSupport: true,
    docsUrl: "https://apidocs.hibob.com",
    logoEmoji: "👥",
    popularity: "MEDIUM",
    setupComplexity: "LOW",
    connectorRoute: "/api/integrations/hr",
  },
  {
    provider: "ADP",
    category: "HR",
    name: "ADP Workforce Now",
    description: "Payroll and workforce data sync from ADP.",
    authType: "OAUTH2",
    syncDirection: "INBOUND",
    webhookSupport: false,
    docsUrl: "https://developers.adp.com",
    logoEmoji: "💼",
    popularity: "HIGH",
    setupComplexity: "HIGH",
    connectorRoute: "/api/integrations/hr",
  },

  // ── SSO / IDENTITY ────────────────────────────────────────────────────────
  {
    provider: "ENTRA_ID",
    category: "SSO",
    name: "Microsoft Entra ID (Azure AD)",
    description:
      "SAML/OIDC SSO — employees sign in with corporate Microsoft credentials.",
    authType: "SAML",
    syncDirection: "INBOUND",
    webhookSupport: false,
    docsUrl: "https://learn.microsoft.com/en-us/azure/active-directory/",
    logoEmoji: "🟦",
    popularity: "HIGH",
    setupComplexity: "MEDIUM",
    connectorRoute: "/api/integrations/sso",
  },
  {
    provider: "OKTA",
    category: "SSO",
    name: "Okta",
    description:
      "SAML/OIDC SSO and SCIM provisioning via Okta Universal Directory.",
    authType: "SAML",
    syncDirection: "INBOUND",
    webhookSupport: true,
    docsUrl: "https://developer.okta.com",
    logoEmoji: "🔵",
    popularity: "HIGH",
    setupComplexity: "MEDIUM",
    connectorRoute: "/api/integrations/sso",
  },
  {
    provider: "GOOGLE_WORKSPACE",
    category: "SSO",
    name: "Google Workspace",
    description: "Google Sign-In / Workspace SAML SSO and directory sync.",
    authType: "SAML",
    syncDirection: "INBOUND",
    webhookSupport: false,
    docsUrl: "https://developers.google.com/workspace",
    logoEmoji: "🔴",
    popularity: "HIGH",
    setupComplexity: "LOW",
    connectorRoute: "/api/integrations/sso",
  },
  {
    provider: "AUTH0",
    category: "SSO",
    name: "Auth0",
    description:
      "Universal identity platform — OIDC SSO with social and enterprise IDPs.",
    authType: "OAUTH2",
    syncDirection: "INBOUND",
    webhookSupport: true,
    docsUrl: "https://auth0.com/docs",
    logoEmoji: "⚫",
    popularity: "MEDIUM",
    setupComplexity: "MEDIUM",
    connectorRoute: "/api/integrations/sso",
  },
  {
    provider: "ONELOGIN",
    category: "SSO",
    name: "OneLogin",
    description: "SAML SSO and user provisioning with OneLogin.",
    authType: "SAML",
    syncDirection: "INBOUND",
    webhookSupport: false,
    docsUrl: "https://developers.onelogin.com",
    logoEmoji: "🟢",
    popularity: "LOW",
    setupComplexity: "MEDIUM",
    connectorRoute: "/api/integrations/sso",
  },

  // ── ACCESS CONTROL ────────────────────────────────────────────────────────
  {
    provider: "PAXTON_NET2",
    category: "ACCESS_CONTROL",
    name: "Paxton Net2",
    description:
      "Sync badge holders and door events from Paxton Net2 access control.",
    authType: "API_KEY",
    syncDirection: "BIDIRECTIONAL",
    webhookSupport: false,
    docsUrl: "https://www.paxton-access.com/net2/sdk/",
    logoEmoji: "🚪",
    popularity: "HIGH",
    setupComplexity: "MEDIUM",
    connectorRoute: "/api/integrations/access-control",
  },
  {
    provider: "GALLAGHER",
    category: "ACCESS_CONTROL",
    name: "Gallagher Command Centre",
    description:
      "Enterprise access control — cardholder sync and zone-based access rules.",
    authType: "API_KEY",
    syncDirection: "BIDIRECTIONAL",
    webhookSupport: true,
    docsUrl: "https://gallaghersecurity.com/resources/developers/",
    logoEmoji: "🔐",
    popularity: "MEDIUM",
    setupComplexity: "HIGH",
    connectorRoute: "/api/integrations/access-control",
  },
  {
    provider: "HID_ORIGO",
    category: "ACCESS_CONTROL",
    name: "HID Origo",
    description: "Mobile credentials and badge management via HID Origo cloud.",
    authType: "OAUTH2",
    syncDirection: "BIDIRECTIONAL",
    webhookSupport: true,
    docsUrl: "https://hidglobal.com/products/software/origo",
    logoEmoji: "📛",
    popularity: "MEDIUM",
    setupComplexity: "MEDIUM",
    connectorRoute: "/api/integrations/access-control",
  },
  {
    provider: "LENELS2",
    category: "ACCESS_CONTROL",
    name: "LenelS2",
    description: "NetBox/NetVR access control — cardholder and event sync.",
    authType: "API_KEY",
    syncDirection: "BIDIRECTIONAL",
    webhookSupport: false,
    docsUrl: "https://lenels2.com/en/developer",
    logoEmoji: "🔑",
    popularity: "LOW",
    setupComplexity: "HIGH",
    connectorRoute: "/api/integrations/access-control",
  },
  {
    provider: "BRIVO",
    category: "ACCESS_CONTROL",
    name: "Brivo",
    description:
      "Cloud-based access control — sync users, credentials, and site events.",
    authType: "OAUTH2",
    syncDirection: "BIDIRECTIONAL",
    webhookSupport: true,
    docsUrl: "https://developer.brivo.com",
    logoEmoji: "☁️",
    popularity: "MEDIUM",
    setupComplexity: "MEDIUM",
    connectorRoute: "/api/integrations/access-control",
  },
  {
    provider: "GENETEC",
    category: "ACCESS_CONTROL",
    name: "Genetec Security Center",
    description:
      "Unified security platform — access events and badge sync via SDK.",
    authType: "CUSTOM",
    syncDirection: "INBOUND",
    webhookSupport: false,
    docsUrl: "https://developer.genetec.com",
    logoEmoji: "🎥",
    popularity: "MEDIUM",
    setupComplexity: "ENTERPRISE",
    connectorRoute: "/api/integrations/access-control",
  },

  // ── HARDWARE ──────────────────────────────────────────────────────────────
  {
    provider: "ZEBRA",
    category: "HARDWARE",
    name: "Zebra Mobile Computers",
    description:
      "Register and configure Zebra TC/MC handheld computers and RFID readers.",
    authType: "API_KEY",
    syncDirection: "BIDIRECTIONAL",
    webhookSupport: false,
    docsUrl: "https://developer.zebra.com",
    logoEmoji: "🦓",
    popularity: "HIGH",
    setupComplexity: "MEDIUM",
    connectorRoute: "/api/integrations/hardware",
  },
  {
    provider: "ZEBRA_PRINTER",
    category: "HARDWARE",
    name: "Zebra Label Printers",
    description:
      "ZPL label printing to Zebra ZT/ZD series printers via CUPS or direct IP.",
    authType: "API_KEY",
    syncDirection: "OUTBOUND",
    webhookSupport: false,
    docsUrl: "https://developer.zebra.com/docs",
    logoEmoji: "🖨️",
    popularity: "HIGH",
    setupComplexity: "LOW",
    connectorRoute: "/api/integrations/hardware",
  },
  {
    provider: "HONEYWELL_SCANNER",
    category: "HARDWARE",
    name: "Honeywell Scanners",
    description:
      "Honeywell Dolphin/Voyager barcode scanners — register and manage device configurations.",
    authType: "API_KEY",
    syncDirection: "BIDIRECTIONAL",
    webhookSupport: false,
    docsUrl: "https://developer.honeywell.com",
    logoEmoji: "📡",
    popularity: "HIGH",
    setupComplexity: "MEDIUM",
    connectorRoute: "/api/integrations/hardware",
  },
  {
    provider: "DATALOGIC",
    category: "HARDWARE",
    name: "Datalogic",
    description: "Datalogic handheld and fixed barcode scanners management.",
    authType: "API_KEY",
    syncDirection: "BIDIRECTIONAL",
    webhookSupport: false,
    docsUrl:
      "https://www.datalogic.com/eng/support-training/developer-resources.html",
    logoEmoji: "📶",
    popularity: "MEDIUM",
    setupComplexity: "MEDIUM",
    connectorRoute: "/api/integrations/hardware",
  },
  {
    provider: "IMPINJ_RFID",
    category: "HARDWARE",
    name: "Impinj RFID",
    description:
      "RFID reader network management and tag event streaming from Impinj Speedway.",
    authType: "CUSTOM",
    syncDirection: "INBOUND",
    webhookSupport: false,
    docsUrl: "https://developer.impinj.com",
    logoEmoji: "📡",
    popularity: "MEDIUM",
    setupComplexity: "HIGH",
    connectorRoute: "/api/integrations/hardware",
  },
  {
    provider: "SIEMENS_PLC",
    category: "HARDWARE",
    name: "Siemens PLC / SCADA",
    description:
      "Siemens S7 PLC integration via OPC-UA for conveyor and sortation systems.",
    authType: "CUSTOM",
    syncDirection: "BIDIRECTIONAL",
    webhookSupport: false,
    docsUrl: "https://support.industry.siemens.com",
    logoEmoji: "⚙️",
    popularity: "MEDIUM",
    setupComplexity: "ENTERPRISE",
    connectorRoute: "/api/integrations/hardware",
  },
  {
    provider: "ALLEN_BRADLEY",
    category: "HARDWARE",
    name: "Allen-Bradley / Rockwell",
    description:
      "Rockwell Automation PLC integration via EtherNet/IP for material handling.",
    authType: "CUSTOM",
    syncDirection: "BIDIRECTIONAL",
    webhookSupport: false,
    docsUrl: "https://rockwellautomation.com/developer",
    logoEmoji: "🔧",
    popularity: "MEDIUM",
    setupComplexity: "ENTERPRISE",
    connectorRoute: "/api/integrations/hardware",
  },

  // ── ROBOTICS ──────────────────────────────────────────────────────────────
  {
    provider: "AUTOSTORE",
    category: "ROBOTICS",
    name: "AutoStore",
    description:
      "AutoStore grid WCS — task dispatch, bin retrieval, and throughput metrics.",
    authType: "API_KEY",
    syncDirection: "BIDIRECTIONAL",
    webhookSupport: true,
    docsUrl: "https://www.autostoresystem.com/developer",
    logoEmoji: "🤖",
    popularity: "HIGH",
    setupComplexity: "ENTERPRISE",
    connectorRoute: "/api/integrations/robotics",
  },
  {
    provider: "DEMATIC",
    category: "ROBOTICS",
    name: "Dematic",
    description: "Dematic iQ WCS — conveyor, sorter, and AGV task management.",
    authType: "CUSTOM",
    syncDirection: "BIDIRECTIONAL",
    webhookSupport: false,
    docsUrl: "https://www.dematic.com/developer",
    logoEmoji: "🏭",
    popularity: "HIGH",
    setupComplexity: "ENTERPRISE",
    connectorRoute: "/api/integrations/robotics",
  },
  {
    provider: "LOCUS_ROBOTICS",
    category: "ROBOTICS",
    name: "Locus Robotics",
    description:
      "Locus AMR fleet — job dispatch, bot status, and pick confirmation events.",
    authType: "API_KEY",
    syncDirection: "BIDIRECTIONAL",
    webhookSupport: true,
    docsUrl: "https://developer.locusrobotics.com",
    logoEmoji: "🤖",
    popularity: "MEDIUM",
    setupComplexity: "HIGH",
    connectorRoute: "/api/integrations/robotics",
  },
  {
    provider: "GEEK_PLUS",
    category: "ROBOTICS",
    name: "Geek+",
    description:
      "Goods-to-person AMR system — pod dispatch and sorting robot management.",
    authType: "API_KEY",
    syncDirection: "BIDIRECTIONAL",
    webhookSupport: false,
    docsUrl: "https://geekplusrobotics.com/developer",
    logoEmoji: "📦",
    popularity: "MEDIUM",
    setupComplexity: "HIGH",
    connectorRoute: "/api/integrations/robotics",
  },
  {
    provider: "FETCH_ROBOTICS",
    category: "ROBOTICS",
    name: "Fetch Robotics",
    description:
      "Fetch AMR autonomous transport — work order and workflow automation.",
    authType: "OAUTH2",
    syncDirection: "BIDIRECTIONAL",
    webhookSupport: true,
    docsUrl: "https://fetchrobotics.com/developer",
    logoEmoji: "🚗",
    popularity: "LOW",
    setupComplexity: "HIGH",
    connectorRoute: "/api/integrations/robotics",
  },

  // ── TMS / YMS ─────────────────────────────────────────────────────────────
  {
    provider: "FLEETOPS360",
    category: "TMS_YMS",
    name: "FleetOps360",
    description:
      "Yard and fleet management — live vehicle positions, gate events, and dock assignments.",
    authType: "API_KEY",
    syncDirection: "BIDIRECTIONAL",
    webhookSupport: true,
    docsUrl: "https://fleetops360.com/developer",
    logoEmoji: "🚛",
    popularity: "MEDIUM",
    setupComplexity: "MEDIUM",
    connectorRoute: "/api/integrations/tms-yms",
  },
  {
    provider: "SAMSARA",
    category: "TMS_YMS",
    name: "Samsara",
    description:
      "GPS fleet tracking, HOS compliance, and sensor data from Samsara.",
    authType: "OAUTH2",
    syncDirection: "INBOUND",
    webhookSupport: true,
    docsUrl: "https://developers.samsara.com",
    logoEmoji: "📍",
    popularity: "HIGH",
    setupComplexity: "MEDIUM",
    connectorRoute: "/api/integrations/tms-yms",
  },
  {
    provider: "WEBFLEET",
    category: "TMS_YMS",
    name: "Webfleet (TomTom)",
    description:
      "Vehicle telematics and driver behaviour data from Webfleet/TomTom.",
    authType: "OAUTH2",
    syncDirection: "INBOUND",
    webhookSupport: true,
    docsUrl: "https://webfleet.com/en_gb/webfleet-solutions/developer/",
    logoEmoji: "🗺️",
    popularity: "MEDIUM",
    setupComplexity: "MEDIUM",
    connectorRoute: "/api/integrations/tms-yms",
  },
  {
    provider: "TRIMBLE_TMS",
    category: "TMS_YMS",
    name: "Trimble TMS",
    description:
      "Load planning, carrier management, and freight audit with Trimble TMS.",
    authType: "OAUTH2",
    syncDirection: "BIDIRECTIONAL",
    webhookSupport: false,
    docsUrl: "https://transportation.trimble.com/developer",
    logoEmoji: "🚚",
    popularity: "MEDIUM",
    setupComplexity: "HIGH",
    connectorRoute: "/api/integrations/tms-yms",
  },
  {
    provider: "MERCURYGATE",
    category: "TMS_YMS",
    name: "MercuryGate TMS",
    description:
      "MercuryGate cloud TMS — load tendering, track-and-trace, and carrier EDI.",
    authType: "API_KEY",
    syncDirection: "BIDIRECTIONAL",
    webhookSupport: false,
    docsUrl: "https://mercurygate.com/developer",
    logoEmoji: "☿",
    popularity: "LOW",
    setupComplexity: "HIGH",
    connectorRoute: "/api/integrations/tms-yms",
  },

  // ── QMS ───────────────────────────────────────────────────────────────────
  {
    provider: "IAUDITOR",
    category: "QMS",
    name: "iAuditor (SafetyCulture)",
    description:
      "Push CAPA actions and audit findings to iAuditor inspection platform.",
    authType: "API_KEY",
    syncDirection: "BIDIRECTIONAL",
    webhookSupport: true,
    docsUrl: "https://developer.safetyculture.com",
    logoEmoji: "✅",
    popularity: "HIGH",
    setupComplexity: "LOW",
    connectorRoute: "/api/integrations/qms",
  },
  {
    provider: "ECOONLINE",
    category: "QMS",
    name: "EcoOnline",
    description:
      "EHS management — sync safety incidents and chemical COSHH records.",
    authType: "OAUTH2",
    syncDirection: "BIDIRECTIONAL",
    webhookSupport: false,
    docsUrl: "https://www.ecoonline.com/api",
    logoEmoji: "🟢",
    popularity: "MEDIUM",
    setupComplexity: "MEDIUM",
    connectorRoute: "/api/integrations/qms",
  },
  {
    provider: "MASTERCONTROL",
    category: "QMS",
    name: "MasterControl",
    description:
      "ISO-compliant QMS — push nonconformances and CAPAs to MasterControl.",
    authType: "OAUTH2",
    syncDirection: "BIDIRECTIONAL",
    webhookSupport: false,
    docsUrl: "https://www.mastercontrol.com/developer",
    logoEmoji: "📋",
    popularity: "MEDIUM",
    setupComplexity: "HIGH",
    connectorRoute: "/api/integrations/qms",
  },
  {
    provider: "ETQ_RELIANCE",
    category: "QMS",
    name: "ETQ Reliance",
    description:
      "Enterprise QMS — audit management, CAPA, and deviation handling.",
    authType: "OAUTH2",
    syncDirection: "BIDIRECTIONAL",
    webhookSupport: false,
    docsUrl: "https://www.etq.com/api",
    logoEmoji: "🔵",
    popularity: "LOW",
    setupComplexity: "HIGH",
    connectorRoute: "/api/integrations/qms",
  },
  {
    provider: "VEEVA_VAULT",
    category: "QMS",
    name: "Veeva Vault QMS",
    description: "Life-science QMS — deviation, CAPA, and change control sync.",
    authType: "OAUTH2",
    syncDirection: "BIDIRECTIONAL",
    webhookSupport: false,
    docsUrl: "https://developer.veeva.com",
    logoEmoji: "🏥",
    popularity: "LOW",
    setupComplexity: "ENTERPRISE",
    connectorRoute: "/api/integrations/qms",
  },

  // ── IoT CLOUD ─────────────────────────────────────────────────────────────
  {
    provider: "AWS_IOT",
    category: "IOT_CLOUD",
    name: "AWS IoT Core",
    description:
      "Pull sensor telemetry and device shadow state from AWS IoT Core.",
    authType: "API_KEY",
    syncDirection: "INBOUND",
    webhookSupport: false,
    docsUrl: "https://docs.aws.amazon.com/iot/",
    logoEmoji: "☁️",
    popularity: "HIGH",
    setupComplexity: "HIGH",
    connectorRoute: "/api/integrations/iot-cloud",
  },
  {
    provider: "AZURE_IOT",
    category: "IOT_CLOUD",
    name: "Azure IoT Hub",
    description: "Device registry and telemetry ingestion from Azure IoT Hub.",
    authType: "API_KEY",
    syncDirection: "INBOUND",
    webhookSupport: true,
    docsUrl: "https://docs.microsoft.com/en-us/azure/iot-hub/",
    logoEmoji: "🔵",
    popularity: "HIGH",
    setupComplexity: "HIGH",
    connectorRoute: "/api/integrations/iot-cloud",
  },
  {
    provider: "GOOGLE_IOT",
    category: "IOT_CLOUD",
    name: "Google Cloud IoT",
    description:
      "Pub/Sub sensor events and device management via Google Cloud IoT Core.",
    authType: "OAUTH2",
    syncDirection: "INBOUND",
    webhookSupport: false,
    docsUrl: "https://cloud.google.com/iot/docs",
    logoEmoji: "🔴",
    popularity: "MEDIUM",
    setupComplexity: "HIGH",
    connectorRoute: "/api/integrations/iot-cloud",
  },

  // ── VOICE HARDWARE ────────────────────────────────────────────────────────
  {
    provider: "HONEYWELL_VOCOLLECT",
    category: "VOICE_HARDWARE",
    name: "Honeywell Vocollect",
    description:
      "Push operator voice profiles and task lists to Vocollect SRX headsets.",
    authType: "API_KEY",
    syncDirection: "BIDIRECTIONAL",
    webhookSupport: false,
    docsUrl: "https://developer.vocollect.com",
    logoEmoji: "🎧",
    popularity: "HIGH",
    setupComplexity: "HIGH",
    connectorRoute: "/api/integrations/voice-hardware",
  },
  {
    provider: "LYDIA_VOICE",
    category: "VOICE_HARDWARE",
    name: "Lydia Voice",
    description:
      "Lydia voice-directed picking — task sync and operator profile management.",
    authType: "API_KEY",
    syncDirection: "BIDIRECTIONAL",
    webhookSupport: false,
    docsUrl: "https://www.lydia-voice.com/developer",
    logoEmoji: "🎤",
    popularity: "MEDIUM",
    setupComplexity: "HIGH",
    connectorRoute: "/api/integrations/voice-hardware",
  },
  {
    provider: "ANDROID_HEADSET",
    category: "VOICE_HARDWARE",
    name: "Android Voice (BYOD)",
    description:
      "Generic Android headset with TTS/STT — push tasks via REST to voice app.",
    authType: "API_KEY",
    syncDirection: "BIDIRECTIONAL",
    webhookSupport: false,
    docsUrl: "",
    logoEmoji: "📱",
    popularity: "MEDIUM",
    setupComplexity: "MEDIUM",
    connectorRoute: "/api/integrations/voice-hardware",
  },
];

// GET /api/integrations/catalogue
export async function GET(req: NextRequest) {
  const authResult = await requireApiAuth(req);
  if (authResult instanceof NextResponse) return authResult;

  const { searchParams } = new URL(req.url);
  const category = searchParams.get("category")?.toUpperCase();
  const query = searchParams.get("q")?.toLowerCase();

  let results = CATALOGUE;

  if (category && category !== "ALL") {
    results = results.filter((e) => e.category === category);
  }

  if (query) {
    results = results.filter(
      (e) =>
        e.name.toLowerCase().includes(query) ||
        e.description.toLowerCase().includes(query) ||
        e.provider.toLowerCase().includes(query),
    );
  }

  const byCategory = results.reduce<Record<string, CatalogueEntry[]>>(
    (acc, entry) => {
      if (!acc[entry.category]) acc[entry.category] = [];
      acc[entry.category].push(entry);
      return acc;
    },
    {},
  );

  const categories = [...new Set(CATALOGUE.map((e) => e.category))].map(
    (cat) => ({
      id: cat,
      label: cat.replace(/_/g, " ").replace(/\b\w/g, (c) => c.toUpperCase()),
      count: (byCategory[cat] ?? []).length,
      total: CATALOGUE.filter((e) => e.category === cat).length,
    }),
  );

  return NextResponse.json({
    total: results.length,
    categories,
    catalogue: results,
    byCategory,
  });
}
