/**
 * Load Sheet API
 * Real-time load sheet generation and management
 */

import { NextRequest, NextResponse } from 'next/server';
import { getServerSession } from 'next-auth';
import { authOptions } from '@/app/api/auth/[...nextauth]/route';
import { prisma } from '@/lib/prisma';
import { generateLoadSheetNumber } from '@/lib/utils/loadSheetUtils';

// GET /api/loadsheets - List load sheets with filters
export async function GET(request: NextRequest) {
  try {
    const session = await getServerSession(authOptions);
    
    if (!session?.user) {
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
    }
    
    const { searchParams } = new URL(request.url);
    const status = searchParams.get('status');
    const customerId = searchParams.get('customerId');
    const warehouseId = searchParams.get('warehouseId');
    const date = searchParams.get('date');
    const search = searchParams.get('search');
    
    const where: any = {};
    
    if (status) where.status = status;
    if (customerId) where.customerId = customerId;
    if (warehouseId) where.warehouseId = warehouseId;
    if (date) {
      const dateObj = new Date(date);
      const nextDay = new Date(dateObj);
      nextDay.setDate(nextDay.getDate() + 1);
      where.shipmentDate = {
        gte: dateObj,
        lt: nextDay,
      };
    }
    if (search) {
      where.OR = [
        { loadSheetNumber: { contains: search, mode: 'insensitive' } },
        { trailerNumber: { contains: search, mode: 'insensitive' } },
        { driverName: { contains: search, mode: 'insensitive' } },
      ];
    }
    
    const loadSheets = await prisma.loadSheet.findMany({
      where,
      include: {
        customer: {
          select: {
            id: true,
            name: true,
            code: true,
          },
        },
        bayDoor: {
          select: {
            id: true,
            doorNumber: true,
            status: true,
          },
        },
        warehouse: {
          select: {
            id: true,
            name: true,
          },
        },
        containers: {
          include: {
            containerItems: {
              select: {
                id: true,
                sku: true,
                quantity: true,
              },
            },
            _count: {
              select: {
                containerItems: true,
              },
            },
          },
        },
        _count: {
          select: {
            containers: true,
            loadSheetDistributions: true,
          },
        },
      },
      orderBy: { createdAt: 'desc' },
      take: 50,
    });
    
    return NextResponse.json({
      loadSheets,
      count: loadSheets.length,
    });
    
  } catch (error) {
    console.error('Get load sheets error:', error);
    return NextResponse.json(
      { error: 'Failed to retrieve load sheets' },
      { status: 500 }
    );
  }
}

// POST /api/loadsheets - Create new load sheet
export async function POST(request: NextRequest) {
  try {
    const session = await getServerSession(authOptions);
    
    if (!session?.user) {
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
    }
    
    const body = await request.json();
    const {
      shipmentDate,
      customerId,
      destinationAddress,
      destinationBranch,
      routeCode,
      carrierName,
      carrierCode,
      driverName,
      driverPhone,
      trailerNumber,
      warehouseId,
      bayDoorId,
      organizationId,
      generationMethod = 'REALTIME',
      containerIds = [],
    } = body;
    
    if (!shipmentDate || !organizationId) {
      return NextResponse.json(
        { error: 'Shipment date and organization ID are required' },
        { status: 400 }
      );
    }
    
    // Generate load sheet number
    const loadSheetNumber = await generateLoadSheetNumber(organizationId);
    
    // Create load sheet
    const loadSheet = await prisma.loadSheet.create({
      data: {
        loadSheetNumber,
        status: 'BUILDING',
        generationMethod,
        autoGenerated: generationMethod === 'REALTIME',
        shipmentDate: new Date(shipmentDate),
        customerId,
        destinationAddress,
        destinationBranch,
        routeCode,
        carrierName,
        carrierCode,
        driverName,
        driverPhone,
        trailerNumber,
        warehouseId,
        bayDoorId,
        organizationId,
        totalContainers: 0,
        totalWeight: 0,
        totalVolume: 0,
        totalPallets: 0,
        totalBoxes: 0,
        totalItems: 0,
        totalOrders: 0,
      },
      include: {
        customer: true,
        bayDoor: true,
        warehouse: true,
      },
    });
    
    // Assign containers if provided
    if (containerIds.length > 0) {
      await prisma.container.updateMany({
        where: {
          id: { in: containerIds },
        },
        data: {
          loadSheetId: loadSheet.id,
          status: 'READY',
        },
      });
      
      // Recalculate totals
      await recalculateLoadSheetTotals(loadSheet.id);
    }
    
    // Create event
    await prisma.loadSheetEvent.create({
      data: {
        loadSheetId: loadSheet.id,
        eventType: 'CREATED',
        userId: session.user.id,
        userName: session.user.name || 'Unknown',
        automated: generationMethod === 'REALTIME',
        organizationId,
      },
    });
    
    // Get updated load sheet with containers
    const updatedLoadSheet = await prisma.loadSheet.findUnique({
      where: { id: loadSheet.id },
      include: {
        customer: true,
        bayDoor: true,
        warehouse: true,
        containers: {
          include: {
            containerItems: true,
          },
        },
      },
    });
    
    return NextResponse.json({
      success: true,
      loadSheet: updatedLoadSheet,
    }, { status: 201 });
    
  } catch (error) {
    console.error('Create load sheet error:', error);
    return NextResponse.json(
      { error: error instanceof Error ? error.message : 'Failed to create load sheet' },
      { status: 500 }
    );
  }
}

// PATCH /api/loadsheets - Update load sheet
export async function PATCH(request: NextRequest) {
  try {
    const session = await getServerSession(authOptions);
    
    if (!session?.user) {
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
    }
    
    const body = await request.json();
    const { loadSheetId, action, ...updates } = body;
    
    if (!loadSheetId) {
      return NextResponse.json(
        { error: 'Load sheet ID is required' },
        { status: 400 }
      );
    }
    
    const loadSheet = await prisma.loadSheet.findUnique({
      where: { id: loadSheetId },
    });
    
    if (!loadSheet) {
      return NextResponse.json(
        { error: 'Load sheet not found' },
        { status: 404 }
      );
    }
    
    // Handle specific actions
    if (action === 'approve') {
      const approved = await prisma.loadSheet.update({
        where: { id: loadSheetId },
        data: {
          approved: true,
          approvedBy: session.user.id,
          approvedAt: new Date(),
          status: 'CONFIRMED',
          approvalNotes: updates.approvalNotes,
        },
        include: {
          containers: true,
          customer: true,
        },
      });
      
      await prisma.loadSheetEvent.create({
        data: {
          loadSheetId,
          eventType: 'APPROVED',
          userId: session.user.id,
          userName: session.user.name || 'Unknown',
          notes: updates.approvalNotes,
          organizationId: loadSheet.organizationId,
        },
      });
      
      return NextResponse.json({
        success: true,
        loadSheet: approved,
      });
    }
    
    if (action === 'distribute') {
      // Mark as distributed (actual distribution handled by separate endpoint)
      const distributed = await prisma.loadSheet.update({
        where: { id: loadSheetId },
        data: {
          distributed: true,
          distributedAt: new Date(),
          status: 'DISTRIBUTED',
        },
      });
      
      await prisma.loadSheetEvent.create({
        data: {
          loadSheetId,
          eventType: 'DISTRIBUTED',
          userId: session.user.id,
          userName: session.user.name || 'Unknown',
          organizationId: loadSheet.organizationId,
        },
      });
      
      return NextResponse.json({
        success: true,
        loadSheet: distributed,
      });
    }
    
    if (action === 'depart') {
      const departed = await prisma.loadSheet.update({
        where: { id: loadSheetId },
        data: {
          actualDeparture: new Date(),
          status: 'DEPARTED',
        },
      });
      
      // Update containers to shipped
      await prisma.container.updateMany({
        where: { loadSheetId },
        data: {
          status: 'SHIPPED',
          shippedAt: new Date(),
        },
      });
      
      await prisma.loadSheetEvent.create({
        data: {
          loadSheetId,
          eventType: 'DEPARTED',
          userId: session.user.id,
          userName: session.user.name || 'Unknown',
          organizationId: loadSheet.organizationId,
        },
      });
      
      return NextResponse.json({
        success: true,
        loadSheet: departed,
      });
    }
    
    // Regular update
    const updated = await prisma.loadSheet.update({
      where: { id: loadSheetId },
      data: updates,
      include: {
        customer: true,
        bayDoor: true,
        containers: {
          include: {
            containerItems: true,
          },
        },
      },
    });
    
    await prisma.loadSheetEvent.create({
      data: {
        loadSheetId,
        eventType: 'MODIFIED',
        userId: session.user.id,
        userName: session.user.name || 'Unknown',
        eventData: updates,
        organizationId: loadSheet.organizationId,
      },
    });
    
    return NextResponse.json({
      success: true,
      loadSheet: updated,
    });
    
  } catch (error) {
    console.error('Update load sheet error:', error);
    return NextResponse.json(
      { error: 'Failed to update load sheet' },
      { status: 500 }
    );
  }
}

// Helper function to recalculate load sheet totals
async function recalculateLoadSheetTotals(loadSheetId: string) {
  const containers = await prisma.container.findMany({
    where: { loadSheetId },
    include: { containerItems: true },
  });
  
  const totalWeight = containers.reduce((sum, c) => sum + (c.weight || 0), 0);
  const totalVolume = containers.reduce((sum, c) => sum + (c.volume || 0), 0);
  const totalPallets = containers.filter(c => c.containerType === 'PALLET').length;
  const totalBoxes = containers.filter(c => c.containerType === 'BOX').length;
  const totalItems = containers.reduce((sum, c) => sum + c.containerItems.length, 0);
  const totalOrders = new Set(
    containers.flatMap(c => c.containerItems.map(i => i.salesOrderId).filter(Boolean))
  ).size;
  
  await prisma.loadSheet.update({
    where: { id: loadSheetId },
    data: {
      totalContainers: containers.length,
      totalWeight,
      totalVolume,
      totalPallets,
      totalBoxes,
      totalItems,
      totalOrders,
    },
  });
}
